### PR TITLE
#7: write data model in README file

### PR DESCRIPTION
**Pull request by jflora91**

### CODE REVIEW

**Review by daveseco7 — COMMENTED** [review]
Please add another column with the data types (using mysql).

`Date_Create` may not be a suitable name

**Review by daveseco7 — COMMENTED** [review]
Why are you using `TEXT` over `BLOB` or `JSON` ?

**Comment by jflora91** [comment]
> Why are you using `TEXT` over `BLOB` or `JSON` ?

BLOB values are treated as binary strings, so it's better to store data files like images. 
For this project the version of MySQL used doesn't support JSON type yet, just exist from version 5.7.8

**Review by daveseco7 — COMMENTED** [review]
How do you intent to compare 2 versions and check which is the latest ?

**Comment by jflora91** [comment]
> How do you intent to compare 2 versions and check which is the latest ?

By the ID, my idea it's to generate automatically the ID's(incrementing the integer) and the highest value will be always the latest version

**Comment by tsbatista** [comment]
> > How do you intent to compare 2 versions and check which is the latest ?
> 
> By the ID, my idea it's to generate automatically the ID's(incrementing the integer) and the highest value will be always the latest version

Please, never use a database ID to do anything other than uniquely identify the entity. The fact that you are using numeric (not necessarily integer) sequential ID's is an artifact of the implementation, you may well replace it with UUID (very common) and everything should still work the same as long as you keep internal consistency in the process.

Also, if you list the versions of the configuration X and you get say 10, 4523, and 7890345234789, you will probably wonder what happened to the versions in between

**Comment by jflora91** [comment]
> > > How do you intent to compare 2 versions and check which is the latest ?
> > 
> > 
> > By the ID, my idea it's to generate automatically the ID's(incrementing the integer) and the highest value will be always the latest version
> 
> Please, never use a database ID to do anything other than uniquely identify the entity. The fact that you are using numeric (not necessarily integer) sequential ID's is an artifact of the implementation, you may well replace it with UUID (very common) and everything should still work the same as long as you keep internal consistency in the process.
> 
> Also, if you list the versions of the configuration X and you get say 10, 4523, and 7890345234789, you will probably wonder what happened to the versions in between

So the best way to compare version will be the use of created_at field?

**Comment by daveseco7** [comment]
> > > > How do you intent to compare 2 versions and check which is the latest ?
> > > 
> > > 
> > > By the ID, my idea it's to generate automatically the ID's(incrementing the integer) and the highest value will be always the latest version
> > 
> > 
> > Please, never use a database ID to do anything other than uniquely identify the entity. The fact that you are using numeric (not necessarily integer) sequential ID's is an artifact of the implementation, you may well replace it with UUID (very common) and everything should still work the same as long as you keep internal consistency in the process.
> > Also, if you list the versions of the configuration X and you get say 10, 4523, and 7890345234789, you will probably wonder what happened to the versions in between
> 
> So the best way to compare version will be the use of created_at field?

You literally created a column named `version`

**Comment by jflora91** [comment]
> > > > > How do you intent to compare 2 versions and check which is the latest ?
> > > > 
> > > > 
> > > > By the ID, my idea it's to generate automatically the ID's(incrementing the integer) and the highest value will be always the latest version
> > > 
> > > 
> > > Please, never use a database ID to do anything other than uniquely identify the entity. The fact that you are using numeric (not necessarily integer) sequential ID's is an artifact of the implementation, you may well replace it with UUID (very common) and everything should still work the same as long as you keep internal consistency in the process.
> > > Also, if you list the versions of the configuration X and you get say 10, 4523, and 7890345234789, you will probably wonder what happened to the versions in between
> > 
> > 
> > So the best way to compare version will be the use of created_at field?
> 
> You literally created a column named `version`

forget... i understand, by version of course

**Comment by daveseco7** [comment]
> > > > > > How do you intent to compare 2 versions and check which is the latest ?
> > > > > 
> > > > > 
> > > > > By the ID, my idea it's to generate automatically the ID's(incrementing the integer) and the highest value will be always the latest version
> > > > 
> > > > 
> > > > Please, never use a database ID to do anything other than uniquely identify the entity. The fact that you are using numeric (not necessarily integer) sequential ID's is an artifact of the implementation, you may well replace it with UUID (very common) and everything should still work the same as long as you keep internal consistency in the process.
> > > > Also, if you list the versions of the configuration X and you get say 10, 4523, and 7890345234789, you will probably wonder what happened to the versions in between
> > > 
> > > 
> > > So the best way to compare version will be the use of created_at field?
> > 
> > 
> > You literally created a column named `version`
> 
> forget... i understand, by version of course

Ok so does it seems ok to you the dataType of the version colunm ? and what about the ID coulnm ?

**Review by tsbatista — APPROVED** [review]
Good enough to merge in my opinion. There are still a few uncertainties that need to be addressed at a later stage, but they are not solvable at this point in time.

**Comment by daveseco7** [comment]
Seems ok to me 👍

**Pull request merged**
